### ISSUE TITLE
Doesn't start complaining about missing properties

### ISSUE THREAD

**Issue by iocanel** [redhat-ipaas/http-pull-push-example#4]
The exact message is: `hostname must be specified and not empty`

Copying and pasting global configuration as found in the ipaas connectors project (see below) makes it work.

## global options of the HTTP GET connector
http-get.scheme=http
http-get.hostname=localhost
http-get.port=8080
http-get.path=myservice

## global options of the HTTP POST connector
http-post.scheme=http
http-post.hostname=localhost
http-post.port=8080
http-post.path=myotherservice

**Comment by iocanel** [comment]
So we need to either fix this. Or update the way we are generating code to also include those stuff.

My understanding though is that we shouldn't need to provide these stuff.

@jimmidyson, @davsclaus, @chirino: thoughts?

**Comment by davsclaus** [comment]
You need to update the connector versions also so it uses latest release, yeah see that example at
https://github.com/redhat-ipaas/connectors/tree/master/examples/http-pull-push-example

You configure global options in the application.properties, and the funktion.yml file should use shorter urls like in the route: https://github.com/redhat-ipaas/connectors/blob/master/examples/http-pull-push-example/src/main/java/com/redhat/ipaas/example/PullPushRoute.java#L25
